[tool.poetry]
name = "innohassle-search"
version = "0.1.0"
description = "Search service for InNoHassle ecosystem"
authors = ["Nikita <n.sannikov@innopolis.university>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyyaml = "^6.0.1"
colorlog = "^6.8.2"
pydantic = "^2.7.4"
beanie = "^1.26.0"
motor = "^3.4.0"
fastapi = "^0.110.0"
uvicorn = "^0.27.1"
cryptography = "^42.0.5"
authlib = "^1.3.0"
httpx = "^0.27.0"
minio = "^7.2.7"
python-multipart = "^0.0.9"

[tool.poetry.group.dev]
optional = true
[tool.poetry.group.dev.dependencies]
ruff = "^0.4.9"
pre-commit = "^3.6.2"

[tool.ruff]
line-length = 120
lint.ignore = [
    # wildcard imports are fine
    "F403",
    "F405",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
