$schema: https://json-schema.org/draft-07/schema#
$defs:
  Accounts:
    additionalProperties: false
    description: InNoHassle-Accounts integration settings
    properties:
      api_url:
        default: https://api.innohassle.ru/accounts/v0
        description: URL of the Accounts API
        title: Api Url
        type: string
      api_jwt_token:
        description: 'JWT token for accessing the Accounts API as a service.

          Generate it here: https://api.innohassle.ru/accounts/v0/docs#/Tokens/tokens_generate_service_token'
        format: password
        title: Api Jwt Token
        type: string
        writeOnly: true
    required:
    - api_jwt_token
    title: Accounts
    type: object
  ApiSettings:
    additionalProperties: false
    properties:
      app_root_path:
        default: ''
        description: Prefix for the API path (e.g. "/api/v0")
        title: App Root Path
        type: string
      db_url:
        examples:
        - mongodb://username:password@localhost:27017/db?authSource=admin
        format: password
        title: Db Url
        type: string
        writeOnly: true
    required:
    - db_url
    title: ApiSettings
    type: object
additionalProperties: false
properties:
  $schema:
    default: null
    title: $Schema
    type: string
  api_settings:
    anyOf:
    - $ref: '#/$defs/ApiSettings'
    - type: 'null'
    default: null
  accounts:
    anyOf:
    - $ref: '#/$defs/Accounts'
    - type: 'null'
    default: null
title: Settings
type: object
