$schema: https://json-schema.org/draft-07/schema#
$defs:
  Accounts:
    description: InNoHassle-Accounts integration settings
    properties:
      api_url:
        default: https://api.innohassle.ru/accounts/v0
        description: URL of the Accounts API
        title: Api Url
        type: string
    title: Accounts
    type: object
  ApiSettings:
    properties:
      app_root_path:
        default: ''
        description: Prefix for the API path (e.g. "/api/v0")
        title: App Root Path
        type: string
      cors_allow_origins:
        default:
        - https://innohassle.ru
        - https://pre.innohassle.ru
        - http://localhost:3000
        description: 'Allowed origins for CORS: from which domains requests to the
          API are allowed'
        items:
          type: string
        title: Cors Allow Origins
        type: array
      db_url:
        description: URL of the MongoDB database
        examples:
        - mongodb://username:password@localhost:27017/db?authSource=admin
        format: password
        title: Db Url
        type: string
        writeOnly: true
      compute_service_token:
        default: secret
        description: Access token for the compute service which is used for authentication
        title: Compute Service Token
        type: string
    required:
    - db_url
    title: ApiSettings
    type: object
  ComputeSetting:
    properties:
      api_url:
        default: http://127.0.0.1:8001
        description: URL of the Search API
        title: Api Url
        type: string
      auth_token:
        default: secret
        description: Access token for the compute service which is used for authentication
        title: Auth Token
        type: string
      corpora_update_period:
        default: 10
        description: Period in seconds to fetch corpora from the API
        title: Corpora Update Period
        type: number
      check_search_queue_period:
        default: 0.1
        description: Period in seconds to fetch tasks from the API
        title: Check Search Queue Period
        type: number
      num_workers:
        default: 4
        description: Number of workers to process tasks
        title: Num Workers
        type: integer
    title: ComputeSetting
    type: object
  MinioSettings:
    properties:
      endpoint:
        default: 127.0.0.1:9000
        description: URL of the target service.
        title: Endpoint
        type: string
      access_key:
        description: Access key (user ID) of a user account in the service.
        examples:
        - minioadmin
        title: Access Key
        type: string
      secret_key:
        description: Secret key (password) for the user account.
        examples:
        - password
        format: password
        title: Secret Key
        type: string
        writeOnly: true
    required:
    - access_key
    - secret_key
    title: MinioSettings
    type: object
properties:
  $schema:
    default: null
    title: $Schema
    type: string
  api_settings:
    $ref: '#/$defs/ApiSettings'
  compute_settings:
    $ref: '#/$defs/ComputeSetting'
  accounts:
    $ref: '#/$defs/Accounts'
  minio:
    $ref: '#/$defs/MinioSettings'
title: Settings
type: object
